<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ContactCore.Application/ContactCore.Application.csproj" />
    <ProjectReference Include="../ContactCore.Infrastructure/ContactCore.Infrastructure.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
