<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ContactCore.Domain/ContactCore.Domain.csproj" />
    <ProjectReference Include="../ContactCore.Application/ContactCore.Application.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
