<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ContactCore.Application/ContactCore.Application.csproj" />
    <ProjectReference Include="../ContactCore.Domain/ContactCore.Domain.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
